### ISSUE TITLE
service "needs a restart" is not clear if the user needs to do it or it's done automatically

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-service-restart#1]
After running swupd update/verify, sometimes you get something like this:

   pacdiscovery.service: needs a restart (the binary was updated)
   tallow.service: needs a restart (a library dependency was updated)
   systemd-udevd.service: needs a restart (the binary was updated)

It's not "clear" who the messages are intended for or what the user should do.
* Should the user to reboot the system?  
* Should the user manually restart each of the services listed?  

For users who are not familiar with the innerworkings of Clear, the first reaction is probably to reboot the system. 

If the said services were restarted automatically, then i think it should say that they were restarted and no action needed by the user.  

If the said services were restarted automatically, but failed, then it should say so and ask the user to manually restart.

**Comment by ahkok** [comment]
This has long been fixed:

```
 swupd[13966]: Update was applied.
 swupd[13966]: Calling post-update helper scripts.
 swupd[13966]: clr_debug_fuse.service: restarted (the binary was updated)
 swupd[13966]: pacdiscovery.service: restarted (the binary was updated)
```
